# Base
ARG NODE_VERSION=20.13.1
FROM node:${NODE_VERSION}-slim AS base
ARG PORT=3000
WORKDIR /src
RUN apt-get update && apt-get upgrade -y
RUN npm install -g pnpm

# Install
FROM base AS install
ENV NODE_ENV=development
COPY package.json pnpm-lock.yaml ./
RUN pnpm i
COPY . .

# Run
FROM install
EXPOSE 3000
EXPOSE 24678
CMD [ "npm", "run", "dev" ]